# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build-server
    - run: npm run build-client
    - name: Setup SSH key
      run: echo "${{ secrets.PEM_KEY }}" >> ./key.pem
    - name: Setup SSH key mod
      run: chmod 400 ./key.pem
    - name: Set known hosts
      run: echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ./known_hosts
    - name: Set known hosts mod
      run: chmod 600 ./known_hosts
    - name: Deploy Frontend
      run: scp -r -i ./key.pem -o UserKnownHostsFile=./known_hosts build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }}:pa2020/frontend
    - name: Deploy Backend
      run: scp -r -i ./key.pem -o UserKnownHostsFile=./known_hosts lib/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }}:pa2020/backend
    - name: Restart pm2
      run: ssh -i ./key.pem -o UserKnownHostsFile=./known_hosts ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_ADDRESS }} "pm2 restart all"
