name: PR Checks

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
    - run: pnpm run lint
    - run: pnpm run build-server
    - run: pnpm run build-client
      env:
        VITE_OAUTH_ID: ${{ secrets.REACT_APP_OAUTH_ID }}
        REACT_APP_OAUTH_ID: ${{ secrets.REACT_APP_OAUTH_ID }}
